ALTER TABLE sites ADD COLUMN created_at TIMESTAMP DEFAULT NOW();
ALTER TABLE users ADD COLUMN created_at TIMESTAMP DEFAULT NOW();
ALTER TABLE credentials ADD COLUMN created_at TIMESTAMP DEFAULT NOW();
