ALTER TABLE sites ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW();
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW();
ALTER TABLE credentials ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW();
